version: '3.4'

services:
  authserver-app-production:
    build:
      context: ../
      dockerfile: AuthServer.Web/Dockerfile
    container_name: AuthServer-Application-Production
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_Kestrel__Certificates__Default__Path=./dev-cert.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=111111111
      - ASPNETCORE_URLS=https://+:30020;http://+:3002
    ports:
      - "3002:3002"
      - "30020:30020"
    networks:
      - authserver-production-network

  authserver-sql-production:
    container_name: AuthServer-Sql-Production
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - "1432:1432"
    environment:
      - "ACCEPT_EULA=1"
      - "MSSQL_SA_PASSWORD=HardProductionPassw0rd1!"
    volumes:
      - "./data/production/mssql/data/:/var/opt/mssql/data/"
      - "./data/production/mssql/log/:/var/opt/mssql/log/"
      - "./data/production/mssql/secrets/:/var/opt/mssql/secrets/"
    networks:
      - authserver-production-network

networks:
  authserver-production-network:
     name: authserver-production-network